### PR TITLE
Add ephemeral smoke test

### PR DESCRIPTION
**Pull request by bsquizz**
This PR runs an rbac smoke test to help ensure changes to MBOP do not impact ephemeral environments.

After building and pushing a PR image to quay, the pr_check.sh script will modify the ClowdEnvironment for the ephemeral environment that it has reserved and alter the mbop image. After that we wait to see the 'mbop' deployment rollout complete, and then we continue on with running rbac backend+frontend outage tests against the ephemeral env.

### CODE REVIEW

**Comment by bsquizz** [comment]
I need to move the jenkins job to ci.int before this is going to work. Working on the config changes for that ...

**Comment by bsquizz** [comment]
@Victoremepunto is going to review

**Comment by Victoremepunto** [comment]
@bsquizz  great job ! I think it's a great addition to have these E2E tests with RBAC to check everything keeps working. 

I added a small comment, but that's it - I was about to suggest other renames and corresponding updates to the README but I will do it myself in a follow up PR, I'm planning to undo some of the work that was done as part of #15

**Pull request merged**
