### PR TITLE
Define `Store` interface for registering satellites with cognito tokens + PG implementation

### PR DESCRIPTION
**Pull request by lindgrenj6**
This PR defines how we'll pull data from the database (or whatever we use as a store) via an interface and package. 

Also have the initial migration and struct definition for the `Registration` instance. 

---

Open to any discussion needed here. 

\# TODO: 
- [x] `Store` interface
- [x] Postgres DB schema for registrations table
- [x] Migrator setup

~In a future PR built off of this one I'll add the actual postgres datastore implementation (it needs the config package in #33)~ jk, it's all in here.

---

This got a bit bigger than I hoped but it all is kind of related:
1. `Store` interface, super generic and simple
2. A postgres backed implementation and an in-memory implementation (so we don't need to have postgres for example in ephemeral)
3. The initial dependency setup + injection at app startup
4. Database migrations with initial schema.

Best way is to probably go commit by commit, its pretty logical that way.

### CODE REVIEW

**Comment by lphiri** [comment]
@coderbydesign  @lindgrenj6  - it occurred to me that this could be generally useful and work with direct RHEL system connections as well.   I see the code is pretty generic (good)   - not seeing the API spec  but can  we make sure that is also generic and not Satellite specific?

**Comment by lindgrenj6** [comment]
@lphiri sure, I could add a `type` column to the db as well if we wanted to. Have that be an enum we could edit as we see fit. 

I haven't started on the API yet but will probably by the end of the week.

**Comment by lindgrenj6** [comment]
cc @aleccohan not sure why it won't let me request you as a reviewer.

**Review by aleccohan — APPROVED** [review]
looks great to me!  I really like the inMemoryStore implementation!

**Review by coderbydesign — APPROVED** [review]

**Pull request merged**
